### ISSUE TITLE
Define @Transactional at the class level

### ISSUE THREAD

**Issue by jamesdh** [srachoor/SpecialOccasionTexterWeb#2]
https://github.com/srachoor/SpecialOccasionTexterWeb/blob/78e6ed040d66599ae3761971b6aeece64b5d6e3d/src/main/java/com/spoctexter/UserProfileLayer/UserProfileService.java#L13-L14

It's probably easier to just define @Transactional at the class level and not per method. That will probably solve some of your issues regarding detached objects. So...

```java
@Service
@Transactional
class UserProfileService {
```

...and then you don't need to define @Transactional on any methods unless you intend to override some of the default transactional characteristics (unlikely)

**Comment by srachoor** [comment]
I appreciate the note on this one. I actually wasn't using my UserProfileService in Application's Command Line Runner -- it was set up to be used later instead of working directly with the repository. So not sure it caused detached objects but will take a look and try again!
